apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    name: my-app
spec:
  template:
    metadata:
      labels:
        app: my-app
      namespace: dev
    spec:
      containers:
        - name: my-container
          image: httpd:latest 
          ports:
          - name: http
            containerPort: 80
  selector:
    app: my-app

  replicas: 5