apiVersion: v1 
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
  namespace: dev
spec:
  containers:
    - name: my-container
      image: httpd:latest 
      ports:
        - name: http
          containerPort: 80
