apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    name: demo-app
spec:
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-container
          image: httpd:latest 
          ports:
          - name: http
            containerPort: 80
  selector:
    matchLabels:
      app: demo-app

  replicas: 5